package esm.dnd.DnDDAM2EnriqueSergioMangel.modelo;

public enum CatEquipo {

	ARMADURA_INTERMEDIA, ARMADURA_LIGERA, ARMADURA_PESADA,
	ARMA_MARCIAL, ARMA_SENCILLA, ESCUDO, HERRAMIENTA, INSTRUMENTO_MUSICAL,
	JUEGO, KIT, MONTURA, MUNICION, OTROS, PAQUETE_DE_EQUIPO, VEHICULO;
}
