package esm.dnd.DnDDAM2EnriqueSergioMangel.modelo;

public enum PropiedadEquipo {

	ALCANCE, ARROJADIZO, CARGADOR, DE_CARGA, DESVENTAJA, DISTANCIA, DOS_MANOS, ESPECIAL, FOCO_ARCANO, FOCO_DUIDRICO, 
	FUERZA, LIGERO, MUNICION, MUNICION_ESPECIAL, PESADO, RAFAGA, SIMBOLO_SAGRADO, SINTONIZADO, SUTIL, VERSATIL;
}
