export enum EnumCatEquipo{
  ARMADURA_INTERMEDIA="ARMADURA_INTERMEDIA",
  ARMADURA_LIGERA="ARMADURA_LIGERA",
  ARMADURA_PESADA="ARMADURA_PESADA",
	ARMA_MARCIAL="ARMA_MARCIAL",
  ARMA_SENCILLA="ARMA_SENCILLA",
  ESCUDO="ESCUDO",
  HERRAMIENTA="HERRAMIENTA",
  INSTRUMENTO_MUSICAL="INSTRUMENTO_MUSICAL",
	JUEGO="JUEGO",
  KIT="KIT",
  MONTURA="MONTURA",
  MUNICION="MUNICION",
  OTROS="OTROS",
  PAQUETE_DE_EQUIPO="PAQUETE_DE_EQUIPO",
  VEHICULO="VEHICULO"
}
