export enum EnumClase{
  BARBARO="BARBARO",
  BARDO="BARDO",
  BRUJO="BRUJO",
  CLERIGO="CLERIGO",
  DRUIDA="DRUIDA",
  EXPLORADOR="EXPLORADOR",
  GUERRERO="GUERRERO",
  HECHICERO="HECHICERO",
  MAGO="MAGO",
  MONJE="MONJE",
  PALADIN="PALADIN",
  PICARO="PICARO",
  SELECCIONAR="SELECCIONAR"
}
