export enum EnumRaza{
  DRACONIDO="DRACONIDO",
  ELFO="ELFO",
  ENANO="ENANO",
  GNOMO="GNOMO",
  HUMANO="HUMANO",
  MEDIANO="MEDIANO",
  SEMIELFO="SEMIELFO",
  SEMIORCO="SEMIORCO",
  TIFLIN="TIFLIN",
  SELECCIONAR="SELECCIONAR"
}
