export enum EnumAlineamiento{
  LEGAL_BUENO="LEGAL_BUENO",
  NEUTRAL_BUENO="NEUTRAL_BUENO",
  CAOTICO_BUENO="CAOTICO_BUENO",
  LEGAL_NEUTRAL="LEGAL_NEUTRAL",
  NEUTRAL="NEUTRAL",
  CAOTICO_NEUTRAL="CAOTICO_NEUTRAL",
  LEGAL_MALO="LEGAL_MALO",
  NEUTRAL_MALO="NEUTRAL_MALO",
  CAOTICO_MALO="CAOTICO_MALO",
  SELECCIONAR="SELECCIONAR"
}
